apiVersion: v1
kind: Service
metadata:
  name: elastic-app-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: elastic-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8501
